### ISSUE TITLE
Install fails due to build dependencies changing

### ISSUE THREAD

**Issue by wldcordeiro** [ANXS/git#1]
When you run this playbook it's failing because libssl has gone from 2.4 to 2.5, adding update_cache to the build dependencies task fixes this issue.

``` yaml
- name: Git | Make sure the build dependencies are installed
  apt:
    update_cache: yes
    pkg: "{{item}}"
    state: present
  with_items: ["libcurl4-openssl-dev", "libexpat1-dev", "libz-dev", "libssl-dev"]
```
